"""Add first_name last_name

Revision ID: ffcb7d56efa2
Revises: eb4bd72da14c
Create Date: 2025-11-27 11:23:16.768529

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffcb7d56efa2"
down_revision: Union[str, None] = "eb4bd72da14c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
