"""add tasks table

Revision ID: eb4bd72da14c
Revises: d1d592a1df80
Create Date: 2025-11-22 11:38:00.410565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb4bd72da14c"
down_revision: Union[str, None] = "d1d592a1df80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column(
            "title",
            sa.String(length=200),
            nullable=False,
            comment="Short title of the task (max 200 characters)",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Optional detailed description of the task",
        ),
        sa.Column(
            "user_id", sa.Integer(), nullable=False, comment="ID of the user who created task"
        ),
        sa.Column(
            "category_id",
            sa.Integer(),
            nullable=True,
            comment="ID of the category assigned to this task (optional)",
        ),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", name="priority_enum", create_constraint=True),
            nullable=False,
            comment="Task priority (low, medium, high)",
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "completed", name="status_enum", create_constraint=True),
            nullable=False,
            comment="Task status (pending, completed)",
        ),
        sa.Column(
            "due_date",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Deadline of the task (optional)",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the task was marked completed",
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was last updated",
        ),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_tasks_priority", "tasks", ["priority"], unique=False)
    op.create_index("idx_tasks_status", "tasks", ["status"], unique=False)
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_user_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
    op.drop_index("idx_tasks_status", table_name="tasks")
    op.drop_index("idx_tasks_priority", table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
